---
title: "licor"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(janitor)
library(readr)
library(rstatix)
#install.packages("FSA")
library(FSA)
#install.packages("rcompanion")
library(rcompanion)
```

You can add options to executable code like this

```{r}
resp_data <- list.files(path = "/Users/pramodhegde/Library/CloudStorage/OneDrive-UniversityofGeorgia/Documents/Licor",
                        pattern = "*.csv",
                        full.names = T) %>% 
  lapply(read.csv) %>% 
  bind_rows 
new_colnames <- as.character(resp_data[1,])
colnames(resp_data) <- new_colnames
resp_data_w <- resp_data %>% 
  na.omit() 
resp_data_w <- resp_data_w %>% 
  filter(!row_number() %in% c(1,2,93,94,185,186,277,278,369,370,461,462,553,554,645,646,737,738,830,831,922,923)) 
#write_csv("../output/combined_soilresp.csv")
  
 
  
  
```


Taking out outliers, but not recommended
```{r}
remove_outliers <- function(x, na.rm = TRUE, ...) {
  qnt <- quantile(x, probs=c(.25, .75), na.rm = na.rm, ...)
  H <- 1.5 * IQR(x, na.rm = na.rm)
  y <- x
  y[x < (qnt[1] - H)] <- NA
  y[x > (qnt[2] + H)] <- NA
  y
}
```

Removed 29 outliers. 





```{r}
resp_data_w <- resp_data_w %>% 
  clean_names() %>% 
  mutate(date_time_initial_value = as.POSIXct(date_time_initial_value, tz = Sys.timezone(), format="%Y/%m/%d %H:%M:%S")) %>% 
  mutate(label = factor(label)) %>% 
 mutate_if(is.character, as.numeric) %>% 
  mutate(daym = day(date_time_initial_value)) %>% 
  mutate(month = month(date_time_initial_value)) %>% 
  mutate(treatment = case_when( label %in% c(1,8,12,20,23) ~ "Disturbance",
                                label %in% c(2,9,11,19,25) ~ "NPK_Cessation",
                                label %in% c(3,10,14,17,24) ~ "NPK",
                                label %in% c(4,7,15,16,22) ~ "Control", 
                                label %in% c(5,6,13,18,21) ~ "NPK+Disturbance",
                                .default = "Outside_treatments"
    )) %>% 
  na.omit() %>% 
  filter(!swc_2_mean < 0)  %>% 
  mutate( drying_cycle = case_when( daym ==29 & month == 01 ~ "1",
                                    daym == 30 & month == 01 ~"1" ,
                                    daym == 31 & month == 01 ~ "1", 
                                    daym == 05 ~ "2", 
                                    daym == 06 ~ "2", 
                                    daym == 07 ~ "2",
                                    daym == 27 & month == 03 ~ "3",
                                    daym== 28 & month == 03 ~ "3",
                                    daym == 29 & month == 03 ~ "3",
                                    daym == 01 & month == 04 ~ "3", 
                                    .default = "0"
                                    
    
    
    
  )) %>% 
  
   mutate(drying_cycle = factor(drying_cycle)) %>% 
  mutate(treatment = factor(treatment)) %>% 
  mutate(dar = case_when(
    daym ==29 & month == 01 ~ "1",
    daym == 30 & month == 01 ~"2" ,
    daym == 31 & month == 01 ~ "3",
    daym == 05 ~ "1",
    daym == 06 ~ "2",
    daym == 07 ~ "3",
    daym == 27 & month == 03 ~ "1",
     daym== 28 & month == 03 ~ "2",
    daym == 29 & month == 03 ~ "3",
    daym == 01 & month == 04 ~ "6",
    .default = "0"
    
    
  )
           
           ) %>% 
  mutate(dar = factor(dar)) %>% 
  mutate(tod = case_when (hour(date_time_initial_value) < 12 ~ "am",
                            .default = "pm")) %>% 
  mutate(tod = factor(tod)) %>% 
   mutate(rep = case_when
    (label %in% c(1:5) ~ "1",
    label %in% c(6:10) ~ "2",
      label %in% c(11:15) ~ "3",
      label %in% c(16:20) ~ "4", 
      label %in% c(21:25) ~ "5",
      .default = "0"
     )) %>% 
  mutate(rep = factor(rep))
    
    

summary(resp_data_w)

resp_data_wrm <- resp_data_w %>% 
  mutate(swc_2_mean = remove_outliers(swc_2_mean)) %>% 
  na.omit()

resp_data_finalw <- resp_data_wrm %>% 
  group_by(label, daym, month, treatment,drying_cycle,dar,tod) %>% 
  summarise(across(swc_2_mean:ta_mean, mean)) %>% 
  ungroup()


```

The `echo: false` option disables the printing of code (only output is displayed).

```{r}
resp_data_wrm %>% 
  group_by(treatment) %>%
  filter(!treatment == "Outside treatments") %>% 
  ggplot(aes(treatment,fco2_dry))+
  geom_boxplot(aes(color = treatment))+
  scale_y_continuous()+
  labs(x = NULL, y = "soil respiration in umol/m2/s1") +
  theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))+
  scale_fill_viridis_d()+
  theme(legend.position = "none")
  #ggsave("../output/treatmenteffects.jpg")
```

```{r}
resp_data_wrm %>% 
  group_by(label, daym, treatment, drying_cycle, tod, dar) %>% 
  summarise(across(swc_2_mean:ts_2_mean, mean, na.rm = T)) %>% 
  ungroup() %>% 
  filter(drying_cycle ==3) %>% 
  ggplot(aes(dar, fco2_dry))+
  geom_boxplot()+
  facet_wrap(~treatment, scales = "free_y")+
  labs(x = "days after rain",
       y = " soil respiration in umol/m2/s1",
       title = "Drying cycle 1")+
 guides(color = guide_legend(title = "Morning/Afternoon"))
#ggsave("../output/DC3_DARvsSR.jpg")

```
```{r}
resp_data_wrm %>% 
  group_by(label, daym, treatment, drying_cycle, tod, dar) %>% 
  summarise(across(swc_2_mean:ts_2_mean, mean, na.rm = T)) %>% 
  ungroup() %>% 
  filter(drying_cycle ==3) %>% 
  group_by(tod) %>% 
  ggplot(aes(dar, ts_2_mean))+
  geom_boxplot(aes(color = tod))+
  facet_wrap(~treatment, scales = "free_y")+
  labs(x = "days after rain",
       y = " soil temperature",
       title = "Drying cycle 3")+
 guides(color = guide_legend(title = "Morning/Afternoon"))

```

```{r}
resp_data_wrm %>% 
  filter(drying_cycle ==3) %>% 
  ggplot(aes(ta_mean, fco2_dry))+
  geom_point(aes(color = treatment))+
  geom_smooth(method = lm)+
  labs(x = "soil temperature (C)",
       y = "Soil respiration (umol/m2/s)",
       title = "Drying cycle 3")
  
```
```{r}
resp_data_wrm %>% 
  filter(treatment == "NPK + Disturbance", drying_cycle ==3) %>%
  ggplot(aes(ts_2_mean, fco2_dry))+
  geom_point()+
  geom_smooth(method = lm)+
  labs(x = "soil temperature (C)",
       y = "Soil respiration (umol/m2/s)",
       title = "Drying cycle 3")
```


```{r}
resp_data_wrm %>% 
  filter(drying_cycle ==3) %>% 
  ggplot(aes(swc_2_mean, fco2_dry))+
  geom_point()+
  stat_smooth(method = lm)+
  facet_wrap(~treatment)
#ggsave("../output/SRvsSM.jpg")
```

```{r}
resp_data_wrm %>% 
  filter(treatment == "NPK + Disturbance", drying_cycle ==3) %>%
  ggplot(aes(swc_2_mean, fco2_dry))+
  geom_point()+
  geom_smooth(method = lm)+
  labs(x = "soil temperature (C)",
       y = "Soil respiration (umol/m2/s)",
       title = "Drying cycle 3")
```
Grouping disturbed and undisturbed plots 
```{r}
resp_data_finalw %>% 
 mutate(Treatment = case_when(
   treatment == "Disturbance" ~ "Disturbed", 
   treatment == "NPK + Disturbance" ~ "Disturbed", 
   .default = "Undisturbed"
 )) %>% 
  group_by(Treatment,tod) %>% 
  filter(drying_cycle == 2) %>% 
  filter(!treatment == "Outside treatments") %>% 
  ggplot(aes(dar, swc_2_mean)) + 
  geom_boxplot(aes(color = Treatment, fill = tod), alpha = 0.3) +
  labs(x = "Days after rain",
       y = "Soil respiration",
       title = "Drying cycle 3")+
  scale_fill_viridis_d()

```
Comparing plots within disturbed plots 
```{r}
resp_distvsundist <- resp_data_finalw %>% 
 mutate(group = case_when(
   treatment == "Disturbance" ~ "Disturbed", 
   treatment == "NPK + Disturbance" ~ "Disturbed", 
   .default = "Undisturbed"
 )) %>% 
  mutate(group = factor(group))

resp_distvsundist %>% 
  filter(group == "Disturbed") %>% 
  ggplot(aes(treatment, fco2_dry)) +
  geom_boxplot()+
  facet_wrap(~drying_cycle)
  
```
```{r}
resp_data_finalw %>% 
  group_by(treatment) %>% 
  get_summary_stats(fco2_dry, type = "common")
```



Kruskall-Wallis test
```{r}
kruskal.test(fco2_dry ~ treatment, data = resp_data_finalw)
pwc <- pairwise.wilcox.test(resp_data_finalw$fco2_dry, resp_data_finalw$treatment,
                     p.adjust.methods = "BH")


```

```{r}
dunnt <- dunnTest(x = resp_data_finalw$fco2_dry, g = resp_data_finalw$treatment, method = "bonferroni")
dunns <- dunnt$res
cld <- cldList(comparison = dunns$Comparison,
               p.value = dunns$P.adj,
               threshold = 0.05) %>% 
  filter(!Group == "Outside_treatments")
names(cld)[1] <- "treatment"
```

```{r}
resp_data_finalw %>% 
  group_by(treatment) %>%
  filter(!treatment == "Outside_treatments") %>% 
  ggplot(aes(treatment,fco2_dry))+
  geom_boxplot(aes(color = treatment))+
  scale_y_continuous()+
  labs(x = NULL, y = "soil respiration in umol/m2/s1") +
  theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5))+
  scale_fill_viridis_d()+
  theme(legend.position = "none")+
  geom_text(data = cld, aes(label = cld$Letter,y = 4, x = treatment), 
            vjust = -0.5,
            hjust= 0.5,
            fontface = "bold",
            size=3.5,
            check_overlap = F)
```

